please:
	# rustc -crate-name accelsim --edition=2021 --emit=obj examples/accelsim/src/lib.rs
	# ../../target/debug/deps
	# clang++ ../../target/debug/deps/accelsim.o ../../target/debug/build/accelsim-a67c1762e4619dad/out/libinstrumentation.so -shared -o please.so

	clang++ ../../target/debug/libaccelsim.a
